parameters:
    oro_address.importexport.address_normalizer.class: Oro\Bundle\AddressBundle\ImportExport\Serializer\Normalizer\AddressNormalizer
    oro_address.importexport.typed_address_normalizer.class: Oro\Bundle\AddressBundle\ImportExport\Serializer\Normalizer\TypedAddressNormalizer

services:
    oro_address.importexport.address_normalizer:
        class: %oro_address.importexport.address_normalizer.class%

    oro_address.importexport.typed_address_normalizer:
        class: %oro_address.importexport.typed_address_normalizer.class%
        arguments: [@oro_address.importexport.address_normalizer]
