Oro\Bundle\AddressBundle\Entity\AddressBase:
    properties:
        street:
            - NotBlank: ~
            - Length:
                  max: 500

        street2:
            - Length:
                  max: 500

        city:
            - NotBlank: ~
            - Length:
                  max: 255

        postalCode:
            - NotBlank: ~
            - Length:
                  max: 20

        country:
            - NotBlank: ~

        firstName:
            - Length:
                  max: 255

        lastName:
            - Length:
                  max: 255
    constraints:
        - Callback:
            methods: [isStateValid]