oro_api:
    relations:
        Oro\Bundle\AddressBundle\Entity\AbstractAddress:
            '0':
                definition:
                    exclusion_policy: none
                    fields:
                        owner:
                            exclude: true
                        country:
                            fields: name
                        region:
                            fields: name
        Oro\Bundle\AddressBundle\Entity\AbstractTypedAddress:
            '0':
                definition:
                    exclusion_policy: none
                    fields:
                        types:
                            fields: name
                            orderBy:
                                name: ASC
        Oro\Bundle\AddressBundle\Entity\AbstractEmail:
            '0':
                definition:
                    exclusion_policy: all
                    fields:
                        email: ~
                        primary: ~
                    orderBy:
                        primary: DESC
        Oro\Bundle\AddressBundle\Entity\AbstractPhone:
            '0':
                definition:
                    exclusion_policy: all
                    fields:
                        phone: ~
                        primary: ~
                    orderBy:
                        primary: DESC
