oro_entity_virtual_fields:
    OroCRM\Bundle\ContactBundle\Entity\ContactAddress:
        country_virtual:
            query:
                select:
                    expr:         country.name
                    return_type:  string
                join:
                    left:
                        - { join: entity.country, alias: country }

    Oro\Bundle\AddressBundle\Entity\AbstractAddress:
        region_hierarchy:
            query:
                select:
                    expr:         region.name
                    return_type:  string
                join:
                    left:
                        - { join: entity.region, alias: region }
