oro_entity:
    exclude:
        - { entity: Oro\Bundle\AddressBundle\Entity\AbstractAddress, field: regionText }

    virtual_fields:
        Oro\Bundle\AddressBundle\Entity\AbstractAddress:
            country_name:
                query:
                    select:
                        expr:         country.name
                        return_type:  string
                    join:
                        left:
                            - { join: entity.country, alias: country }

            country_iso2_code:
                query:
                    select:
                        expr:         country.iso2Code
                        return_type:  string
                    join:
                        left:
                            - { join: entity.country, alias: country }

            country_iso3_code:
                query:
                    select:
                        expr:         country.iso3Code
                        return_type:  string
                    join:
                        left:
                            - { join: entity.country, alias: country }

            region_name:
                query:
                    select:
                        expr:         region.name
                        return_type:  string
                    join:
                        left:
                            - { join: entity.region, alias: region }

            region_code:
                query:
                    select:
                        expr:         region.code
                        return_type:  string
                    join:
                        left:
                            - { join: entity.region, alias: region }

