#
# FOR TESTING virtual fields with hierarchycal configuration
# REMOVE this before merge
#
oro_entity_virtual_fields:
    Oro\Bundle\AddressBundle\Entity\Address:
        countryName:
            query:
                select:
                    expr:         country.name
                    return_type:  string
                join:
                    left:
                        - { join: entity.country, alias: country }

        countryIso2Code:
            query:
                select:
                    expr:         country.iso2Code
                    return_type:  string
                left:
                    inner:
                        - { join: entity.country, alias: country }

        countryIso3Code:
            query:
                select:
                    expr:         country.iso3Code as countryIso3Code
                    return_type:  string
                left:
                    inner:
                        - { join: entity.country, alias: country }


    Oro\Bundle\AddressBundle\Entity\AbstractAddress:
        regionName:
            query:
                select:
                    expr:         region.name
                    return_type:  string
                join:
                    left:
                        - { join: entity.region, alias: region }

        regionCode:
            query:
                select:
                    expr:         region.code
                    return_type:  string
                join:
                    left:
                        - { join: entity.region, alias: region }

