oro_entity:
    virtual_fields:
        Oro\Bundle\AddressBundle\Entity\AbstractAddress:
            region_name:
                query:
                    select:
                        expr: COALESCE(entity.regionText, region.name)
                        return_type: string
                    join:
                        left:
                            - { join: entity.region, alias: region }
