oro_address_api:
    resource: Oro\Bundle\AddressBundle\Controller\Api\Rest\AddressController
    type: rest
    prefix: api/rest/{version}/
    defaults:
        version: latest

oro_address_type_api:
    resource: Oro\Bundle\AddressBundle\Controller\Api\Rest\AddressTypeController
    type: rest
    prefix: api/rest/{version}/
    defaults:
        version: latest

oro_countries_api:
    resource: Oro\Bundle\AddressBundle\Controller\Api\Rest\CountryController
    type: rest
    prefix: api/rest/{version}/
    defaults:
        version: latest

oro_regions_api:
    resource: Oro\Bundle\AddressBundle\Controller\Api\Rest\RegionController
    type: rest
    prefix: api/rest/{version}/
    defaults:
        version: latest

oro_country_regions_api:
    resource: Oro\Bundle\AddressBundle\Controller\Api\Rest\CountryRegionsController
    type: rest
    prefix: api/rest/{version}/
    defaults:
        version: latest
